import { Locale, Translations } from "../types";

const translations: Record<Locale, Translations> = {
    'en-US': {
        // App.tsx
        errorModelFirst: "Please upload a model image first.",
        errorProductFirst: "Please add at least one product to generate a look.",
        errorGenerateImage: "Failed to generate image. Please try again.",
        errorGenerateImageFirst: "Please generate an image first.",
        errorApiKey: "API Key error. Please re-select your API key.",
        errorGenerateVideo: "Failed to generate video. Please try again.",
        errorUnexpected: "An unexpected error occurred",
        addProducts: "Add Products",
        lightningClick: "Lightning Click",
        styling: "Styling...",
        generateLook: "Generate Look",
        creatingVideo: "Creating Video...",
        createVideo: "Create Video",
        // ModelUploader.tsx
        uploadYourPhoto: "1. Upload Your Photo",
        modelPreviewAlt: "Model preview",
        clickToUpload: "Click to upload a photo",
        imageFormats: "PNG, JPG, or GIF",
        changePhoto: "Change Photo",
        selectPhoto: "Select Photo",
        // ProductUploader.tsx
        remove: "Remove",
        selectFit: "Select Fit",
        selectFabric: "Select Fabric",
        stylingNotesPlaceholder: "Styling notes (e.g., 'a bit larger')",
        // ResultDisplay.tsx
        printTitle: "Print StyleSync Look",
        generatingLook: "Generating Your Look...",
        magicInProgress: "The AI stylist is working its magic!",
        generatedLookAlt: "Generated look",
        modelAlt: "Model",
        styleAwaits: "Your Style Awaits",
        uploadInstructions: "Upload a photo and add products to see your virtual try-on.",
        save: 'Save',
        print: 'Print',
        // LightningCaptureModal.tsx
        lightningTryOn: "Lightning Try-On",
        step1: "Step 1: Capture Your Photo",
        step2: "Step 2: Capture the Product",
        capture: "Capture",
        processing: "Processing...",
        generatingFinalLook: "Identifying product and generating final look...",
        // geminiService.ts
        stylePrompt: "You are an expert virtual stylist. Your task is to realistically place the following clothing and accessory items onto the person in the first image. Maintain the person's original pose, proportions, and the background. Ensure the items blend naturally with the lighting and shadows of the original photo. Here are the items and where they should be placed:",
        placeItemOn: "Place this item on the person's",
        fitPrompt: "It should have a",
        fabricPrompt: "It is made of",
        notesPrompt: "Additional styling notes:",
        errorNoImageGenerated: "No image was generated by the API.",
        videoPrompt: "Create a short, realistic video of this person making a subtle movement, like a slight turn or a gentle sway, to model the outfit. The background should remain consistent.",
        videoGenerated: "Video generated! Fetching data...",
        errorDownloadVideo: "Failed to download video",
        errorNoDownloadLink: "Video generation completed, but no download link was provided.",
        identifyPrompt: `Analyze this image of a clothing item. Identify what it is (e.g., 't-shirt', 'hat', 'sneakers') and which body part it's for. Respond in JSON format with "productName" and "bodyPart" using one of these categories: Head, Face, Neck, Chest, Shoulders, Torso, Arms, Waist, Legs, Feet.`,
        errorIdentification: "Could not identify the product or its appropriate body part.",
        theItemIs: "The item is a",
        // Body parts & adjustments
        head: 'head', face: 'face', neck: 'neck', chest: 'chest', shoulders: 'shoulders', torso: 'torso', arms: 'arms', waist: 'waist', legs: 'legs', feet: 'feet',
        tight: 'tight fit', regular: 'regular fit', loose: 'loose fit',
        cotton: 'cotton', denim: 'denim', leather: 'leather', silk: 'silk', wool: 'wool',
    },
    'pt-BR': {
        // App.tsx
        errorModelFirst: "Por favor, carregue uma foto sua primeiro.",
        errorProductFirst: "Por favor, adicione pelo menos um produto para gerar um look.",
        errorGenerateImage: "Falha ao gerar a imagem. Tente novamente.",
        errorGenerateImageFirst: "Por favor, gere uma imagem primeiro.",
        errorApiKey: "Erro na chave de API. Por favor, selecione sua chave novamente.",
        errorGenerateVideo: "Falha ao gerar o vídeo. Tente novamente.",
        errorUnexpected: "Ocorreu um erro inesperado",
        addProducts: "Adicionar Produtos",
        lightningClick: "Clique Relâmpago",
        styling: "Estilizando...",
        generateLook: "Gerar Look",
        creatingVideo: "Criando Vídeo...",
        createVideo: "Criar Vídeo",
        // ModelUploader.tsx
        uploadYourPhoto: "1. Envie Sua Foto",
        modelPreviewAlt: "Prévia do modelo",
        clickToUpload: "Clique para enviar uma foto",
        imageFormats: "PNG, JPG, ou GIF",
        changePhoto: "Trocar Foto",
        selectPhoto: "Selecionar Foto",
        // ProductUploader.tsx
        remove: "Remover",
        selectFit: "Caimento",
        selectFabric: "Tecido",
        stylingNotesPlaceholder: "Notas de estilo (ex: 'um pouco maior')",
        // ResultDisplay.tsx
        printTitle: "Imprimir Look StyleSync",
        generatingLook: "Gerando Seu Look...",
        magicInProgress: "A estilista IA está fazendo sua mágica!",
        generatedLookAlt: "Look gerado",
        modelAlt: "Modelo",
        styleAwaits: "Seu Estilo te Espera",
        uploadInstructions: "Envie uma foto e adicione produtos para seu provador virtual.",
        save: 'Salvar',
        print: 'Imprimir',
        // LightningCaptureModal.tsx
        lightningTryOn: "Provador Relâmpago",
        step1: "Passo 1: Capture Sua Foto",
        step2: "Passo 2: Capture o Produto",
        capture: "Capturar",
        processing: "Processando...",
        generatingFinalLook: "Identificando o produto e gerando o look final...",
        // geminiService.ts
        stylePrompt: "Você é um(a) estilista virtual especialista. Sua tarefa é posicionar realisticamente as seguintes peças de roupa e acessórios na pessoa da primeira imagem. Mantenha a pose original da pessoa, proporções e o fundo. Garanta que os itens se misturem naturalmente com a iluminação e sombras da foto original. Aqui estão os itens e onde devem ser colocados:",
        placeItemOn: "Posicione este item no(a)",
        fitPrompt: "Deve ter um caimento",
        fabricPrompt: "É feito de",
        notesPrompt: "Notas de estilo adicionais:",
        errorNoImageGenerated: "Nenhuma imagem foi gerada pela API.",
        videoPrompt: "Crie um vídeo curto e realista desta pessoa fazendo um movimento sutil, como um leve giro ou balanço suave, para modelar o look. O fundo deve permanecer consistente.",
        videoGenerated: "Vídeo gerado! Buscando dados...",
        errorDownloadVideo: "Falha ao baixar o vídeo",
        errorNoDownloadLink: "Geração de vídeo concluída, mas nenhum link para download foi fornecido.",
        identifyPrompt: `Analise esta imagem de uma peça de roupa. Identifique o que é (ex: 'camiseta', 'chapéu', 'tênis') e para qual parte do corpo se destina. Responda em formato JSON com "productName" e "bodyPart" usando uma destas categorias: Head, Face, Neck, Chest, Shoulders, Torso, Arms, Waist, Legs, Feet.`,
        errorIdentification: "Não foi possível identificar o produto ou a parte do corpo apropriada.",
        theItemIs: "O item é um(a)",
        // Body parts & adjustments
        head: 'cabeça', face: 'rosto', neck: 'pescoço', chest: 'peito', shoulders: 'ombros', torso: 'tronco', arms: 'braços', waist: 'cintura', legs: 'pernas', feet: 'pés',
        tight: 'justo', regular: 'normal', loose: 'largo',
        cotton: 'algodão', denim: 'jeans', leather: 'couro', silk: 'seda', wool: 'lã',
    }
};

let currentLocale: Locale = 'en-US';
if (typeof navigator !== 'undefined') {
    const browserLang = navigator.language;
    if (browserLang.startsWith('pt')) {
        currentLocale = 'pt-BR';
    }
}

export const getTranslator = () => {
    const translationSet = translations[currentLocale];
    return (key: string): string => translationSet[key] || key;
};
